### ISSUE TITLE
组件优化建议

### ISSUE THREAD

**Issue by jianjianghui** [lfcleo/fc-admin#2]
在淡入新内容之前，完全淡出内容。这避免了部分透明元素的重叠导致分散注意力和混乱的框架。

如果需要发生交叉淡入淡出，请保持快速并在过渡最快的部分将其隐藏。

![image](https://github.com/user-attachments/assets/35199db8-7f68-4719-b4e0-43681221ff78)

**Comment by lfcleo** [comment]
OK，后续优化

**Comment by lfcleo** [comment]
已经完成
