### ISSUE TITLE
表格操作列按钮多了能否隐藏现在更多按钮

### ISSUE THREAD

**Issue by falcon-jin** [lfcleo/fc-admin#3]
![image](https://github.com/user-attachments/assets/2475bc67-25dc-477f-bdda-8d2c4ac89fd8)
类似这个组件 https://opentiny.design/tiny-vue/zh-CN/os-theme/components/action-menu

**Comment by lfcleo** [comment]
这个自己实现下吧。每个人需求的都不一样，不可能面面俱到。你也可以把这个想要的组件导入到项目中使用。
